import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import type { Metadata } from "next";
import { Jost, Figtree } from "next/font/google";
import Link from "next/link";

const jost = Jost({ subsets: ["latin"] });
const figtree = Figtree({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all pages

  const pages = await getPages();

  const today = new Date();
  const yyyy = today.getFullYear();

  return (
    <html lang="en">
      <body className={`${figtree.className} p-10 flex flex-col min-h-screen`}>
        <header className="flex items-center justify-between">
          <Link href="/" className="text-lg font-bold uppercase">
            repetition world
          </Link>

          <div className="flex items-center gap-3">
            {/* {pages.map((page) => {
              return (
                <Link
                  key={page._id}
                  href={`/${page.slug}`}
                  className="hover:underline text-sm uppercase"
                >
                  {page.title}
                </Link>
              );
            })} */}
            <Link
              href="/about"
              className="hover:underline text-sm uppercase"
            >
              about
            </Link>
            <Link
              href="contact"
              className="hover:underline text-sm uppercase"
            >
              contact
            </Link>
          </div>
        </header>

        <main className="py-20 flex-1">{children}</main>

        <footer>
          <p className="text-xs text-center">&copy; {yyyy}</p>
        </footer>
      </body>
    </html>
  );
}
